<h1>
 Title: Catch Block
</h1>
<h3>
 Author: Anonymous
</h3>
<h3>
 Date: 2021-09-12T01:11:43.347844+10:00
</h3>
<h3>
 Category: General
</h3>
<h3>
 Vote Count: 0
</h3>
<p>
 Can catch blocks catch exceptions in each other?
</p>
<p>
 In other words, can a catch block in the same try-catch block, catch an exception thrown in the catch block above it?
</p>
<h3>
 ----------- REPLIES -----------
</h3>
<div style="text-indent: 2em;">
 <h3>
  Author: David Gries (admin)
 </h3>
 <h3>
  Vote Count: 0
 </h3>
 <p>
  No. That it not how it works.
 </p>
 <p>
  If you read carefully how a try-statement is executed, you could answer that question yourself.
 </p>
 <p>
  Only objects thrown in the try-clause can be caught in a catch block.
 </p>
 <h3>
  ------------------------------------
 </h3>
</div>