<h1>
 Title: catch-block question
</h1>
<h3>
 Author: Anonymous
</h3>
<h3>
 Date: 2021-10-06T05:00:36.00777+11:00
</h3>
<h3>
 Category: General
</h3>
<h3>
 Vote Count: 0
</h3>
<document version="2.0">
 <paragraph>
  if a catch-block throws an exception that another catch-block can deal with, does it get thrown to that catch-block?
 </paragraph>
</document>
<h3>
 ----------- REPLIES -----------
</h3>
<h3>
 Author: Varun Gande (student)
</h3>
<h3>
 Vote Count: 0
</h3>
<document version="2.0">
 <paragraph>
  No, if it's not in its own try block.
 </paragraph>
</document>
<h3>
 ------------------------------------
</h3>
<h3>
 Author: Anonymous
</h3>
<h3>
 Vote Count: 0
</h3>
<document version="2.0">
 <paragraph>
  Ok, and then if a try-block calls 2 different exceptions can only one be called? Because once it's caught it will leave the try-block right?
 </paragraph>
</document>
<h3>
 ------------------------------------
</h3>
<h3>
 Author: Varun Gande (student)
</h3>
<h3>
 Vote Count: 0
</h3>
<document version="2.0">
 <paragraph>
  Yes. Only the first exception will be thrown and then caught by a catch statement if it exists.
 </paragraph>
</document>
<h3>
 ------------------------------------
</h3>